[package]
name = "freefi"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.0-rc0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.1" }

[tool.snforge]


[[target.starknet-contract]]
casm = true
sierra = true

# path = "nimbora_toolkit/contracts/l2/src/pooling4626/pooling4626.cairo"